/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
///



///
//////
///
///    Like and Dislike Icons
/// 
/// 
import 'package:flutter/widgets.dart';

class LikeDislike {
  LikeDislike._();

  static const _kFontFam = 'LikeDislike';

  static const IconData thumbs_up_alt = const IconData(0xf164, fontFamily: _kFontFam);
  static const IconData thumbs_down_alt = const IconData(0xf165, fontFamily: _kFontFam);
}